name: brain-segm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - ca-certificates
  - openssl
  - monai
  - matplotlib
  - jupyter
  - tqdm
  - isort
  - certifi
  - flake8
  - mypy
  - black
