name: brain-segm
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - torchvision
  - pytorch
  - torchaudio
  - gdown
  - albumentations
  - flake8
  - h5py
  - black
  - einops
  - certifi
  - imageio
  - isort
  - mypy
  - mlflow
  - lmdb
  - matplotlib
  - pydicom
  - nibabel
  - pandas
  - nilearn
  - pynrrd
  - ignite
  - tqdm
  - transformers
  - scikit-image
  - tensorboard
  - scikit-learn
  - seaborn
  - scipy
  - anaconda::jupyter
  - monai
  - conda-forge::pydantic
