name: brain-segm
channels:
  - conda-forge
dependencies:
  - albumentations
  - black
  - ca-certificates
  - certifi
  - einops
  - flake8
  - gdown
  - h5py
  - imageio
  - isort
  - jupyter
  - lmdb
  - matplotlib
  - mlflow
  - monai
  - mypy
  - nibabel
  - nilearn
  - openssl
  - pandas
  - pydicom
  - pynrrd
  - python
  - pytorch
  - pytorch-ignite
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tensorboard
  - torchvision
  - tqdm
  - transformers
